2025-04-22 11:02:37,965 - ERROR - [anonymous] [http_error] [http://10.4.0.4:5002/login] - HTTP 401 - POST /login
2025-04-22 11:03:24,472 - INFO - [likitha] [bulk_delete] [20.5.9.7] - Bulk delete: 1 servers
2025-04-22 11:03:55,210 - INFO - [likitha] [bulk_delete] [10.5.6.8, 40.5.9.1] - Bulk delete: 2 servers
2025-04-22 11:04:18,746 - INFO - [likitha] [shutdown] [10.4.0.13] - Executing shutdown on 10.4.0.13
2025-04-22 11:04:18,992 - INFO - [likitha] [shutdown] [10.4.0.13] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-22 11:04:19,061 - INFO - [likitha] [shutdown] [10.4.0.13] - Command executed: date
Exit code: 0
STDOUT: Tue Apr 22 11:04:19 UTC 2025
STDERR: None
2025-04-22 11:04:19,131 - INFO - [likitha] [shutdown] [10.4.0.13] - Command executed: uptime -p
Exit code: 0
STDOUT: up 3 hours, 8 minutes
STDERR: None
2025-04-22 11:04:19,202 - INFO - [likitha] [shutdown] [10.4.0.13] - Command executed: free -h
Exit code: 0
STDOUT: total        used        free      shared  buff/cache   available\nMem:           925M        196M        120M        6.2M        608M        583M\nSwap:            0B          0B          0B
STDERR: None
2025-04-22 11:04:19,272 - INFO - [likitha] [shutdown] [10.4.0.13] - Command executed: df -h
Exit code: 0
STDOUT: Filesystem      Size  Used Avail Use% Mounted on\ndevtmpfs        453M     0  453M   0% /dev\ntmpfs           463M     0  463M   0% /dev/shm\ntmpfs           463M  6.2M  457M   2% /run\ntmpfs           463M     0  463M   0% /sys/fs/cgroup\n/dev/sda2        30G  2.4G   27G   8% /\n/dev/sda1       494M   92M  403M  19% /boot\n/dev/sda15      495M   12M  484M   3% /boot/efi\n/dev/sdb1       3.9G   16M  3.7G   1% /mnt/resource\ntmpfs            93M     0   93M   0% /run/user/1152801110
STDERR: None
2025-04-22 11:04:19,433 - INFO - [likitha] [shutdown] [10.4.0.13] - Command executed: sudo shutdown -h now
Exit code: -1
STDOUT: None
STDERR: None
2025-04-22 11:04:33,194 - ERROR - [likitha] [shutdown] [10.2.4.6] - Command failed: shutdown on 10.2.4.6 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 482, in run_command
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-22 11:07:09,565 - INFO - [likitha] [reboot] [10.4.0.13] - Executing reboot on 10.4.0.13
2025-04-22 11:07:09,813 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-22 11:07:09,877 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: date
Exit code: 0
STDOUT: Tue Apr 22 11:07:09 UTC 2025
STDERR: None
2025-04-22 11:07:09,945 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: uptime -p
Exit code: 0
STDOUT: up 1 minute
STDERR: None
2025-04-22 11:07:10,010 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: free -h
Exit code: 0
STDOUT: total        used        free      shared  buff/cache   available\nMem:           925M        203M        553M        6.2M        168M        580M\nSwap:            0B          0B          0B
STDERR: None
2025-04-22 11:07:10,080 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: df -h
Exit code: 0
STDOUT: Filesystem      Size  Used Avail Use% Mounted on\ndevtmpfs        453M     0  453M   0% /dev\ntmpfs           463M     0  463M   0% /dev/shm\ntmpfs           463M  6.2M  457M   2% /run\ntmpfs           463M     0  463M   0% /sys/fs/cgroup\n/dev/sda2        30G  2.4G   27G   8% /\n/dev/sda1       494M   92M  403M  19% /boot\n/dev/sda15      495M   12M  484M   3% /boot/efi\n/dev/sdb1       3.9G   16M  3.7G   1% /mnt/resource\ntmpfs            93M     0   93M   0% /run/user/1152801110
STDERR: None
2025-04-22 11:07:10,158 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: systemctl list-units --type=service --state=running --no-legend | awk '{print $1}'
Exit code: 0
STDOUT: atd.service\nauditd.service\nchronyd.service\ncrond.service\ndbus.service\ngetty@tty1.service\nhypervkvpd.service\nlibstoragemgmt.service\nlvm2-lvmetad.service\nNetworkManager.service\noddjobd.service\npolkit.service\npostfix.service\nrngd.service\nrpcbind.service\nrsyslog.service\nserial-getty@ttyS0.service\nsmartd.service\nsshd.service\nsssd.service\nsystemd-journald.service\nsystemd-logind.service\nsystemd-udevd.service\ntuned.service\nwaagent.service
STDERR: None
2025-04-22 11:07:10,333 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: sudo shutdown -r now
Exit code: -1
STDOUT: None
STDERR: None
2025-04-22 11:07:24,022 - ERROR - [likitha] [reboot] [10.2.4.6] - Command failed: reboot on 10.2.4.6 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 482, in run_command
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-22 11:10:11,165 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: uptime -p || uptime
Exit code: 0
STDOUT: up 2 minutes
STDERR: None
2025-04-22 11:10:11,243 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: systemctl list-units --type=service --state=running --no-legend | awk '{print $1}'
Exit code: 0
STDOUT: atd.service\nauditd.service\nchronyd.service\ncrond.service\ndbus.service\ngetty@tty1.service\nhypervkvpd.service\nlibstoragemgmt.service\nlvm2-lvmetad.service\nNetworkManager.service\noddjobd.service\npolkit.service\npostfix.service\nrngd.service\nrpcbind.service\nrsyslog.service\nserial-getty@ttyS0.service\nsmartd.service\nsshd.service\nsssd.service\nsystemd-journald.service\nsystemd-logind.service\nsystemd-udevd.service\ntuned.service\nwaagent.service
STDERR: None
2025-04-22 11:11:09,519 - INFO - [likitha] [patch_update] [10.4.0.13] - Patch check on 10.4.0.13
2025-04-22 11:11:23,841 - ERROR - [likitha] [patch_update] [10.2.4.6] - Patch operation failed on 10.2.4.6 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 795, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-22 11:11:25,827 - INFO - [likitha] [patch_update] [10.4.0.13] - Command executed: sudo yum clean all && sudo yum makecache
Exit code: 0
STDOUT: Loaded plugins: langpacks\nCleaning repos: base-openlogic extras-openlogic updates-openlogic base extras\n              : openlogic updates\nLoaded plugins: langpacks\nMetadata Cache Created
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-22 11:11:28,589 - INFO - [likitha] [patch_update] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-22 11:12:29,575 - INFO - [likitha] [patch_update] [10.4.0.13] - Patch apply on 10.4.0.13
2025-04-22 11:12:43,867 - ERROR - [likitha] [patch_update] [10.2.4.6] - Patch operation failed on 10.2.4.6 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 795, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-22 11:12:45,322 - INFO - [likitha] [patch_update] [10.4.0.13] - Command executed: sudo yum clean all && sudo yum makecache
Exit code: 0
STDOUT: Loaded plugins: langpacks\nCleaning repos: base-openlogic extras-openlogic updates-openlogic base extras\n              : openlogic updates\nLoaded plugins: langpacks\nMetadata Cache Created
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-22 11:12:47,558 - INFO - [likitha] [patch_update] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-22 11:12:48,589 - INFO - [likitha] [patch_and_reboot] [10.4.0.13] - Command executed: needs-restarting -r &> /dev/null; echo $?
Exit code: 0
STDOUT: 0
STDERR: None
2025-04-22 11:13:57,711 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: top -bn1 | grep 'Cpu(s)' | awk '{print $2+$4}'
Exit code: 0
STDOUT: 12.5
STDERR: None
2025-04-22 11:13:57,783 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: free | awk '/Mem:/ {printf("%.2f", $3/$2 * 100.0)}'
Exit code: 0
STDOUT: 21.79
STDERR: None
2025-04-22 11:13:57,851 - INFO - [likitha] [compliance_check] [10.4.0.13] - Compliance check OS detection: centos
2025-04-22 11:13:58,776 - INFO - [likitha] [compliance_check] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-22 11:13:58,841 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: [ -f /var/run/reboot-required ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: None
2025-04-22 11:13:58,911 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: df -h | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: None
2025-04-22 11:13:58,978 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: df -i | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: None
2025-04-22 11:13:59,045 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: cat /proc/loadavg | awk '{print $1, $2, $3}'
Exit code: 0
STDOUT: 0.10 0.41 0.29
STDERR: None
2025-04-22 11:13:59,123 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: sudo ufw status | grep 'Status: active'
Exit code: 1
STDOUT: None
STDERR: sudo: ufw: command not found
2025-04-22 11:13:59,216 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: sudo sshd -t
Exit code: 0
STDOUT: None
STDERR: None
2025-04-22 11:13:59,282 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: uptime -p || uptime
Exit code: 0
STDOUT: up 6 minutes
STDERR: None
2025-04-22 11:13:59,348 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: uname -r
Exit code: 0
STDOUT: 3.10.0-1160.119.1.el7.x86_64
STDERR: None
2025-04-22 11:13:59,497 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: timedatectl | grep 'System clock synchronized'
Exit code: 1
STDOUT: None
STDERR: None
2025-04-22 11:13:59,596 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: sudo diff <(cat /etc/fstab | grep -v '^#') <(df -h | awk '{print $1}')
Exit code: 2
STDOUT: None
STDERR: diff: /dev/fd/63: No such file or directory\ndiff: /dev/fd/62: No such file or directory
2025-04-22 11:13:59,661 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: getenforce
Exit code: 127
STDOUT: None
STDERR: bash: getenforce: command not found
2025-04-22 11:14:11,821 - INFO - [likitha] [health_check] [10.2.4.6, 10.4.0.13] - Action COMPLETED - health_check on 2 servers
2025-04-22 11:17:50,880 - INFO - [likitha] [reboot] [10.4.0.13] - Executing reboot on 10.4.0.13
2025-04-22 11:17:51,103 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-22 11:17:51,172 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: date
Exit code: 0
STDOUT: Tue Apr 22 11:17:51 UTC 2025
STDERR: None
2025-04-22 11:17:51,246 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: uptime -p
Exit code: 0
STDOUT: up 10 minutes
STDERR: None
2025-04-22 11:17:51,315 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: free -h
Exit code: 0
STDOUT: total        used        free      shared  buff/cache   available\nMem:           925M        201M        139M        6.2M        585M        577M\nSwap:            0B          0B          0B
STDERR: None
2025-04-22 11:17:51,382 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: df -h
Exit code: 0
STDOUT: Filesystem      Size  Used Avail Use% Mounted on\ndevtmpfs        453M     0  453M   0% /dev\ntmpfs           463M     0  463M   0% /dev/shm\ntmpfs           463M  6.2M  457M   2% /run\ntmpfs           463M     0  463M   0% /sys/fs/cgroup\n/dev/sda2        30G  2.4G   27G   8% /\n/dev/sda1       494M   92M  403M  19% /boot\n/dev/sda15      495M   12M  484M   3% /boot/efi\n/dev/sdb1       3.9G   16M  3.7G   1% /mnt/resource\ntmpfs            93M     0   93M   0% /run/user/1152801110
STDERR: None
2025-04-22 11:17:51,458 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: systemctl list-units --type=service --state=running --no-legend | awk '{print $1}'
Exit code: 0
STDOUT: atd.service\nauditd.service\nchronyd.service\ncrond.service\ndbus.service\ngetty@tty1.service\nhypervkvpd.service\nlibstoragemgmt.service\nlvm2-lvmetad.service\nNetworkManager.service\noddjobd.service\npolkit.service\npostfix.service\nrngd.service\nrpcbind.service\nrsyslog.service\nserial-getty@ttyS0.service\nsmartd.service\nsshd.service\nsssd.service\nsystemd-journald.service\nsystemd-logind.service\nsystemd-udevd.service\ntuned.service\nwaagent.service
STDERR: None
2025-04-22 11:17:51,657 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: sudo shutdown -r now
Exit code: -1
STDOUT: None
STDERR: None
2025-04-22 11:18:05,416 - ERROR - [likitha] [reboot] [10.2.4.6] - Command failed: reboot on 10.2.4.6 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 482, in run_command
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-22 11:20:52,521 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: uptime -p || uptime
Exit code: 0
STDOUT: up 2 minutes
STDERR: None
2025-04-22 11:20:52,601 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: systemctl list-units --type=service --state=running --no-legend | awk '{print $1}'
Exit code: 0
STDOUT: atd.service\nauditd.service\nchronyd.service\ncrond.service\ndbus.service\ngetty@tty1.service\nhypervkvpd.service\nlibstoragemgmt.service\nlvm2-lvmetad.service\nNetworkManager.service\noddjobd.service\npolkit.service\npostfix.service\nrngd.service\nrpcbind.service\nrsyslog.service\nserial-getty@ttyS0.service\nsmartd.service\nsshd.service\nsssd.service\nsystemd-journald.service\nsystemd-logind.service\nsystemd-udevd.service\ntuned.service\nwaagent.service
STDERR: None
2025-04-22 11:35:25,797 - INFO - [likitha] [shutdown] [10.4.0.13] - Executing shutdown on 10.4.0.13
2025-04-22 11:35:26,016 - INFO - [likitha] [shutdown] [10.4.0.13] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-22 11:35:26,081 - INFO - [likitha] [shutdown] [10.4.0.13] - Command executed: date
Exit code: 0
STDOUT: Tue Apr 22 11:35:26 UTC 2025
STDERR: None
2025-04-22 11:35:26,147 - INFO - [likitha] [shutdown] [10.4.0.13] - Command executed: uptime -p
Exit code: 0
STDOUT: up 17 minutes
STDERR: None
2025-04-22 11:35:26,214 - INFO - [likitha] [shutdown] [10.4.0.13] - Command executed: free -h
Exit code: 0
STDOUT: total        used        free      shared  buff/cache   available\nMem:           925M        201M        555M        6.2M        169M        583M\nSwap:            0B          0B          0B
STDERR: None
2025-04-22 11:35:26,282 - INFO - [likitha] [shutdown] [10.4.0.13] - Command executed: df -h
Exit code: 0
STDOUT: Filesystem      Size  Used Avail Use% Mounted on\ndevtmpfs        453M     0  453M   0% /dev\ntmpfs           463M     0  463M   0% /dev/shm\ntmpfs           463M  6.2M  457M   2% /run\ntmpfs           463M     0  463M   0% /sys/fs/cgroup\n/dev/sda2        30G  2.4G   27G   8% /\n/dev/sda1       494M   92M  403M  19% /boot\n/dev/sda15      495M   12M  484M   3% /boot/efi\n/dev/sdb1       3.9G   16M  3.7G   1% /mnt/resource\ntmpfs            93M     0   93M   0% /run/user/1152801110
STDERR: None
2025-04-22 11:35:26,459 - INFO - [likitha] [shutdown] [10.4.0.13] - Command executed: sudo shutdown -h now
Exit code: -1
STDOUT: None
STDERR: None
2025-04-22 11:35:40,258 - ERROR - [likitha] [shutdown] [10.2.4.6] - Command failed: shutdown on 10.2.4.6 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 482, in run_command
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-22 11:47:27,052 - ERROR - [likitha] [reboot] [10.2.4.6] - Command failed: reboot on 10.2.4.6 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 482, in run_command
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-22 11:47:27,053 - ERROR - [likitha] [reboot] [10.4.0.13] - Command failed: reboot on 10.4.0.13 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 482, in run_command
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-22 11:57:44,456 - ERROR - [likitha] [shutdown] [10.4.0.13] - Command failed: shutdown on 10.4.0.13 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 482, in run_command
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-22 11:57:44,456 - ERROR - [likitha] [shutdown] [10.2.4.6] - Command failed: shutdown on 10.2.4.6 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 482, in run_command
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-22 12:07:17,730 - ERROR - [likitha] [shutdown] [10.2.4.6] - Command failed: shutdown on 10.2.4.6 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 482, in run_command
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-22 12:07:17,730 - ERROR - [likitha] [shutdown] [10.4.0.13] - Command failed: shutdown on 10.4.0.13 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 482, in run_command
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-22 12:07:53,136 - ERROR - [anonymous] [http_error] [http://10.4.0.4:5002/login] - HTTP 401 - POST /login
2025-04-22 12:12:38,379 - ERROR - [anonymous] [http_error] [http://10.4.0.4:5002/login] - HTTP 401 - POST /login
2025-04-23 04:00:04,645 - ERROR - [anonymous] [http_error] [http://10.4.0.4:5002/favicon.ico] - HTTP 404 - GET /favicon.ico
2025-04-23 04:03:06,626 - INFO - [sushrut] [bulk_delete] [10.2.4.6] - Bulk delete: 1 servers
2025-04-23 04:03:31,484 - INFO - [sushrut] [server_create] [10.4.0.46] - Server created: 10.4.0.46
2025-04-23 04:04:24,261 - INFO - [sushrut] [shutdown] [10.4.0.13] - Executing shutdown on 10.4.0.13
2025-04-23 04:04:24,471 - INFO - [sushrut] [shutdown] [10.4.0.13] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:04:24,524 - INFO - [sushrut] [shutdown] [10.4.0.13] - Command executed: date
Exit code: 0
STDOUT: Wed Apr 23 04:04:24 UTC 2025
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:04:24,589 - INFO - [sushrut] [shutdown] [10.4.0.13] - Command executed: uptime -p
Exit code: 0
STDOUT: up 8 minutes
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:04:24,643 - INFO - [sushrut] [shutdown] [10.4.0.13] - Command executed: free -h
Exit code: 0
STDOUT: total        used        free      shared  buff/cache   available\nMem:           925M        205M        551M        6.2M        169M        578M\nSwap:            0B          0B          0B
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:04:24,698 - INFO - [sushrut] [shutdown] [10.4.0.13] - Command executed: df -h
Exit code: 0
STDOUT: Filesystem      Size  Used Avail Use% Mounted on\ndevtmpfs        453M     0  453M   0% /dev\ntmpfs           463M     0  463M   0% /dev/shm\ntmpfs           463M  6.3M  457M   2% /run\ntmpfs           463M     0  463M   0% /sys/fs/cgroup\n/dev/sda2        30G  2.4G   27G   8% /\n/dev/sda1       494M   92M  403M  19% /boot\n/dev/sda15      495M   12M  484M   3% /boot/efi\n/dev/sdb1       3.9G   16M  3.7G   1% /mnt/resource\ntmpfs            93M     0   93M   0% /run/user/0\ntmpfs            93M     0   93M   0% /run/user/1152801109
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:04:24,860 - INFO - [sushrut] [shutdown] [10.4.0.13] - Command executed: sudo shutdown -h now
Exit code: -1
STDOUT: None
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:04:26,788 - ERROR - [sushrut] [shutdown] [10.4.0.46] - Connection failed: 10.4.0.46
2025-04-23 04:06:06,191 - INFO - [sushrut] [health_check] [10.4.0.46, 10.4.0.13] - Action COMPLETED - health_check on 2 servers
2025-04-23 04:07:17,028 - INFO - [sushrut] [health_check] [10.4.0.46, 10.4.0.13] - Action COMPLETED - health_check on 2 servers
2025-04-23 04:10:10,743 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: top -bn1 | grep 'Cpu(s)' | awk '{print $2+$4}'
Exit code: 0
STDOUT: 16.7
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:10:10,800 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: free | awk '/Mem:/ {printf("%.2f", $3/$2 * 100.0)}'
Exit code: 0
STDOUT: 21.94
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:10:10,853 - INFO - [sushrut] [compliance_check] [10.4.0.13] - Compliance check OS detection: centos
2025-04-23 04:10:14,187 - INFO - [sushrut] [compliance_check] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 04:10:14,241 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: [ -f /var/run/reboot-required ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:10:14,299 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: df -h | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:10:14,358 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: df -i | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:10:14,412 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: cat /proc/loadavg | awk '{print $1, $2, $3}'
Exit code: 0
STDOUT: 0.21 0.52 0.26
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:10:14,479 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: sudo ufw status | grep 'Status: active'
Exit code: 1
STDOUT: None
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied\nsudo: ufw: command not found
2025-04-23 04:10:14,557 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: sudo sshd -t
Exit code: 0
STDOUT: None
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:10:14,612 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: uptime -p || uptime
Exit code: 0
STDOUT: up 3 minutes
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:10:14,666 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: uname -r
Exit code: 0
STDOUT: 3.10.0-1160.119.1.el7.x86_64
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:10:14,801 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: timedatectl | grep 'System clock synchronized'
Exit code: 1
STDOUT: None
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:10:14,886 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: sudo diff <(cat /etc/fstab | grep -v '^#') <(df -h | awk '{print $1}')
Exit code: 2
STDOUT: None
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied\ndiff: /dev/fd/63: No such file or directory\ndiff: /dev/fd/62: No such file or directory
2025-04-23 04:10:14,938 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: getenforce
Exit code: 127
STDOUT: None
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied\nbash: getenforce: command not found
2025-04-23 04:10:14,939 - INFO - [sushrut] [health_check] [10.4.0.46, 10.4.0.13] - Action COMPLETED - health_check on 2 servers
2025-04-23 04:38:54,649 - ERROR - [sushrut] [http_error] [http://10.4.0.4:5002/health_check] - HTTP 405 - GET /health_check
2025-04-23 04:39:03,112 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: top -bn1 | grep 'Cpu(s)' | awk '{print $2+$4}'
Exit code: 0
STDOUT: 11.8
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:39:03,169 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: free | awk '/Mem:/ {printf("%.2f", $3/$2 * 100.0)}'
Exit code: 0
STDOUT: 22.23
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:39:03,224 - INFO - [sushrut] [compliance_check] [10.4.0.13] - Compliance check OS detection: centos
2025-04-23 04:39:03,975 - INFO - [sushrut] [compliance_check] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 04:39:04,029 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: [ -f /var/run/reboot-required ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:39:04,087 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: df -h | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:39:04,144 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: df -i | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:39:04,199 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: cat /proc/loadavg | awk '{print $1, $2, $3}'
Exit code: 0
STDOUT: 0.00 0.01 0.05
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:39:04,267 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: sudo ufw status | grep 'Status: active'
Exit code: 1
STDOUT: None
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied\nsudo: ufw: command not found
2025-04-23 04:39:04,343 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: sudo sshd -t
Exit code: 0
STDOUT: None
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:39:04,398 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: uptime -p || uptime
Exit code: 0
STDOUT: up 32 minutes
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:39:04,453 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: uname -r
Exit code: 0
STDOUT: 3.10.0-1160.119.1.el7.x86_64
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:39:04,556 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: timedatectl | grep 'System clock synchronized'
Exit code: 1
STDOUT: None
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:39:04,643 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: sudo diff <(cat /etc/fstab | grep -v '^#') <(df -h | awk '{print $1}')
Exit code: 2
STDOUT: None
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied\ndiff: /dev/fd/63: No such file or directory\ndiff: /dev/fd/62: No such file or directory
2025-04-23 04:39:04,696 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: getenforce
Exit code: 127
STDOUT: None
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied\nbash: getenforce: command not found
2025-04-23 04:39:05,316 - INFO - [sushrut] [health_check] [10.4.0.46, 10.4.0.13] - Action COMPLETED - health_check on 2 servers
2025-04-23 04:39:13,196 - INFO - [sushrut] [patch_update] [10.4.0.13] - Patch check on 10.4.0.13
2025-04-23 04:39:15,620 - ERROR - [sushrut] [patch_update] [10.4.0.46] - Patch operation failed on 10.4.0.46 - [Errno None] Unable to connect to port 22 on 10.4.0.46
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/working-appV3.py", line 796, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 409, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 10.4.0.46
2025-04-23 04:39:29,995 - INFO - [sushrut] [patch_update] [10.4.0.13] - Command executed: sudo yum clean all && sudo yum makecache
Exit code: 0
STDOUT: Loaded plugins: langpacks\nCleaning repos: base-openlogic extras-openlogic updates-openlogic base extras\n              : openlogic updates\nLoaded plugins: langpacks\nMetadata Cache Created
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 04:39:32,853 - INFO - [sushrut] [patch_update] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 04:39:52,315 - INFO - [sushrut] [patch_update] [10.4.0.13] - Patch apply on 10.4.0.13
2025-04-23 04:39:54,724 - ERROR - [sushrut] [patch_update] [10.4.0.46] - Patch operation failed on 10.4.0.46 - [Errno None] Unable to connect to port 22 on 10.4.0.46
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/working-appV3.py", line 796, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 409, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 10.4.0.46
2025-04-23 04:40:06,871 - INFO - [sushrut] [patch_update] [10.4.0.13] - Command executed: sudo yum clean all && sudo yum makecache
Exit code: 0
STDOUT: Loaded plugins: langpacks\nCleaning repos: base-openlogic extras-openlogic updates-openlogic base extras\n              : openlogic updates\nLoaded plugins: langpacks\nMetadata Cache Created
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 04:40:10,006 - INFO - [sushrut] [patch_update] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 04:42:37,026 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: top -bn1 | grep 'Cpu(s)' | awk '{print $2+$4}'
Exit code: 0
STDOUT: 11.8
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:42:37,086 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: free | awk '/Mem:/ {printf("%.2f", $3/$2 * 100.0)}'
Exit code: 0
STDOUT: 21.80
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:42:37,143 - INFO - [sushrut] [compliance_check] [10.4.0.13] - Compliance check OS detection: centos
2025-04-23 04:42:38,040 - INFO - [sushrut] [compliance_check] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 04:42:38,095 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: [ -f /var/run/reboot-required ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:42:38,153 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: df -h | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:42:38,212 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: df -i | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:42:38,267 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: cat /proc/loadavg | awk '{print $1, $2, $3}'
Exit code: 0
STDOUT: 0.04 0.08 0.07
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:42:38,334 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: sudo ufw status | grep 'Status: active'
Exit code: 1
STDOUT: None
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied\nsudo: ufw: command not found
2025-04-23 04:42:38,418 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: sudo sshd -t
Exit code: 0
STDOUT: None
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:42:38,474 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: uptime -p || uptime
Exit code: 0
STDOUT: up 36 minutes
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:42:38,535 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: uname -r
Exit code: 0
STDOUT: 3.10.0-1160.119.1.el7.x86_64
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:42:38,642 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: timedatectl | grep 'System clock synchronized'
Exit code: 1
STDOUT: None
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 04:42:38,727 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: sudo diff <(cat /etc/fstab | grep -v '^#') <(df -h | awk '{print $1}')
Exit code: 2
STDOUT: None
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied\ndiff: /dev/fd/63: No such file or directory\ndiff: /dev/fd/62: No such file or directory
2025-04-23 04:42:38,779 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: getenforce
Exit code: 127
STDOUT: None
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied\nbash: getenforce: command not found
2025-04-23 04:42:39,204 - INFO - [sushrut] [health_check] [10.4.0.46, 10.4.0.13] - Action COMPLETED - health_check on 2 servers
2025-04-23 04:45:44,774 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: top -bn1 | grep 'Cpu(s)' | awk '{print $2+$4}'
Exit code: 0
STDOUT: 11.8
STDERR: None
2025-04-23 04:45:44,842 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: free | awk '/Mem:/ {printf("%.2f", $3/$2 * 100.0)}'
Exit code: 0
STDOUT: 21.84
STDERR: None
2025-04-23 04:45:44,907 - INFO - [likitha] [compliance_check] [10.4.0.13] - Compliance check OS detection: centos
2025-04-23 04:45:45,685 - INFO - [likitha] [compliance_check] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 04:45:45,754 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: [ -f /var/run/reboot-required ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: None
2025-04-23 04:45:45,822 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: df -h | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: None
2025-04-23 04:45:45,889 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: df -i | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: None
2025-04-23 04:45:45,956 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: cat /proc/loadavg | awk '{print $1, $2, $3}'
Exit code: 0
STDOUT: 0.00 0.04 0.05
STDERR: None
2025-04-23 04:45:46,037 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: sudo ufw status | grep 'Status: active'
Exit code: 1
STDOUT: None
STDERR: sudo: ufw: command not found
2025-04-23 04:45:46,126 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: sudo sshd -t
Exit code: 0
STDOUT: None
STDERR: None
2025-04-23 04:45:46,191 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: uptime -p || uptime
Exit code: 0
STDOUT: up 39 minutes
STDERR: None
2025-04-23 04:45:46,257 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: uname -r
Exit code: 0
STDOUT: 3.10.0-1160.119.1.el7.x86_64
STDERR: None
2025-04-23 04:45:46,372 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: timedatectl | grep 'System clock synchronized'
Exit code: 1
STDOUT: None
STDERR: None
2025-04-23 04:45:46,472 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: sudo diff <(cat /etc/fstab | grep -v '^#') <(df -h | awk '{print $1}')
Exit code: 2
STDOUT: None
STDERR: diff: /dev/fd/63: No such file or directory\ndiff: /dev/fd/62: No such file or directory
2025-04-23 04:45:46,537 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: getenforce
Exit code: 127
STDOUT: None
STDERR: bash: getenforce: command not found
2025-04-23 04:45:46,980 - INFO - [likitha] [health_check] [10.4.0.46, 10.4.0.13] - Action COMPLETED - health_check on 2 servers
2025-04-23 04:51:39,400 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: top -bn1 | grep 'Cpu(s)' | awk '{print $2+$4}'
Exit code: 0
STDOUT: 11.8
STDERR: None
2025-04-23 04:51:39,467 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: free | awk '/Mem:/ {printf("%.2f", $3/$2 * 100.0)}'
Exit code: 0
STDOUT: 21.84
STDERR: None
2025-04-23 04:51:39,532 - INFO - [likitha] [compliance_check] [10.4.0.13] - Compliance check OS detection: centos
2025-04-23 04:51:40,344 - INFO - [likitha] [compliance_check] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 04:51:40,410 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: [ -f /var/run/reboot-required ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: None
2025-04-23 04:51:41,604 - INFO - [likitha] [health_check] [10.4.0.46, 10.4.0.13] - Action COMPLETED - health_check on 2 servers
2025-04-23 04:51:59,855 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: top -bn1 | grep 'Cpu(s)' | awk '{print $2+$4}'
Exit code: 0
STDOUT: 11.8
STDERR: None
2025-04-23 04:51:59,925 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: free | awk '/Mem:/ {printf("%.2f", $3/$2 * 100.0)}'
Exit code: 0
STDOUT: 22.34
STDERR: None
2025-04-23 04:51:59,993 - INFO - [likitha] [compliance_check] [10.4.0.13] - Compliance check OS detection: centos
2025-04-23 04:52:00,834 - INFO - [likitha] [compliance_check] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 04:52:00,900 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: [ -f /var/run/reboot-required ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: None
2025-04-23 04:52:02,084 - INFO - [likitha] [health_check] [10.4.0.46, 10.4.0.13] - Action COMPLETED - health_check on 2 servers
2025-04-23 04:52:12,655 - INFO - [likitha] [shutdown] [10.4.0.13] - Executing shutdown on 10.4.0.13
2025-04-23 04:52:12,883 - INFO - [likitha] [shutdown] [10.4.0.13] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-23 04:52:12,949 - INFO - [likitha] [shutdown] [10.4.0.13] - Command executed: date
Exit code: 0
STDOUT: Wed Apr 23 04:52:12 UTC 2025
STDERR: None
2025-04-23 04:52:13,018 - INFO - [likitha] [shutdown] [10.4.0.13] - Command executed: uptime -p
Exit code: 0
STDOUT: up 45 minutes
STDERR: None
2025-04-23 04:52:13,084 - INFO - [likitha] [shutdown] [10.4.0.13] - Command executed: free -h
Exit code: 0
STDOUT: total        used        free      shared  buff/cache   available\nMem:           925M        208M        134M        6.3M        582M        570M\nSwap:            0B          0B          0B
STDERR: None
2025-04-23 04:52:13,152 - INFO - [likitha] [shutdown] [10.4.0.13] - Command executed: df -h
Exit code: 0
STDOUT: Filesystem      Size  Used Avail Use% Mounted on\ndevtmpfs        453M     0  453M   0% /dev\ntmpfs           463M     0  463M   0% /dev/shm\ntmpfs           463M  6.3M  457M   2% /run\ntmpfs           463M     0  463M   0% /sys/fs/cgroup\n/dev/sda2        30G  2.4G   27G   8% /\n/dev/sda1       494M   92M  403M  19% /boot\n/dev/sda15      495M   12M  484M   3% /boot/efi\n/dev/sdb1       3.9G   16M  3.7G   1% /mnt/resource\ntmpfs            93M     0   93M   0% /run/user/1152801110
STDERR: None
2025-04-23 04:52:13,558 - INFO - [likitha] [shutdown] [10.4.0.13] - Command executed: sudo shutdown -h now
Exit code: -1
STDOUT: None
STDERR: None
2025-04-23 04:52:15,204 - ERROR - [likitha] [shutdown] [10.4.0.46] - Connection failed: 10.4.0.46
2025-04-23 04:53:18,247 - INFO - [likitha] [health_check] [10.4.0.46, 10.4.0.13] - Action COMPLETED - health_check on 2 servers
2025-04-23 04:53:50,745 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: top -bn1 | grep 'Cpu(s)' | awk '{print $2+$4}'
Exit code: 0
STDOUT: 16.7
STDERR: None
2025-04-23 04:53:50,816 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: free | awk '/Mem:/ {printf("%.2f", $3/$2 * 100.0)}'
Exit code: 0
STDOUT: 22.30
STDERR: None
2025-04-23 04:53:50,886 - INFO - [likitha] [compliance_check] [10.4.0.13] - Compliance check OS detection: centos
2025-04-23 04:53:54,310 - INFO - [likitha] [compliance_check] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 04:53:54,378 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: [ -f /var/run/reboot-required ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: None
2025-04-23 04:53:54,378 - INFO - [likitha] [health_check] [10.4.0.46, 10.4.0.13] - Action COMPLETED - health_check on 2 servers
2025-04-23 04:58:50,135 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: top -bn1 | grep 'Cpu(s)' | awk '{print $2+$4}'
Exit code: 0
STDOUT: 11.8
STDERR: None
2025-04-23 04:58:50,204 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: free | awk '/Mem:/ {printf("%.2f", $3/$2 * 100.0)}'
Exit code: 0
STDOUT: 22.61
STDERR: None
2025-04-23 04:58:50,275 - INFO - [likitha] [compliance_check] [10.4.0.13] - Compliance check OS detection: centos
2025-04-23 04:58:51,198 - INFO - [likitha] [compliance_check] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 04:58:51,265 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: [ -f /var/run/reboot-required ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: None
2025-04-23 04:58:52,324 - INFO - [likitha] [health_check] [10.4.0.46, 10.4.0.13] - Action COMPLETED - health_check on 2 servers
2025-04-23 04:59:13,798 - INFO - [likitha] [reboot] [10.4.0.13] - Executing reboot on 10.4.0.13
2025-04-23 04:59:14,032 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-23 04:59:14,103 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: date
Exit code: 0
STDOUT: Wed Apr 23 04:59:14 UTC 2025
STDERR: None
2025-04-23 04:59:14,216 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: uptime -p
Exit code: 0
STDOUT: up 6 minutes
STDERR: None
2025-04-23 04:59:14,300 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: free -h
Exit code: 0
STDOUT: total        used        free      shared  buff/cache   available\nMem:           925M        211M        368M        6.3M        345M        572M\nSwap:            0B          0B          0B
STDERR: None
2025-04-23 04:59:14,370 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: df -h
Exit code: 0
STDOUT: Filesystem      Size  Used Avail Use% Mounted on\ndevtmpfs        453M     0  453M   0% /dev\ntmpfs           463M     0  463M   0% /dev/shm\ntmpfs           463M  6.3M  457M   2% /run\ntmpfs           463M     0  463M   0% /sys/fs/cgroup\n/dev/sda2        30G  2.4G   27G   8% /\n/dev/sda1       494M   92M  403M  19% /boot\n/dev/sda15      495M   12M  484M   3% /boot/efi\n/dev/sdb1       3.9G   16M  3.7G   1% /mnt/resource\ntmpfs            93M     0   93M   0% /run/user/1152801110
STDERR: None
2025-04-23 04:59:14,449 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: systemctl list-units --type=service --state=running --no-legend | awk '{print $1}'
Exit code: 0
STDOUT: atd.service\nauditd.service\nchronyd.service\ncrond.service\ndbus.service\ngetty@tty1.service\nhypervkvpd.service\nlibstoragemgmt.service\nlvm2-lvmetad.service\nNetworkManager.service\noddjobd.service\npolkit.service\npostfix.service\nrngd.service\nrpcbind.service\nrsyslog.service\nserial-getty@ttyS0.service\nsmartd.service\nsshd.service\nsssd.service\nsystemd-journald.service\nsystemd-logind.service\nsystemd-udevd.service\ntuned.service\nwaagent.service
STDERR: None
2025-04-23 04:59:14,674 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: sudo shutdown -r now
Exit code: -1
STDOUT: None
STDERR: None
2025-04-23 04:59:16,388 - ERROR - [likitha] [reboot] [10.4.0.46] - Connection failed: 10.4.0.46
2025-04-23 05:02:15,542 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: uptime -p || uptime
Exit code: 0
STDOUT: up 2 minutes
STDERR: None
2025-04-23 05:02:15,619 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: systemctl list-units --type=service --state=running --no-legend | awk '{print $1}'
Exit code: 0
STDOUT: atd.service\nauditd.service\nchronyd.service\ncrond.service\ndbus.service\ngetty@tty1.service\nhypervkvpd.service\nlibstoragemgmt.service\nlvm2-lvmetad.service\nNetworkManager.service\noddjobd.service\npolkit.service\npostfix.service\nrngd.service\nrpcbind.service\nrsyslog.service\nserial-getty@ttyS0.service\nsmartd.service\nsshd.service\nsssd.service\nsystemd-journald.service\nsystemd-logind.service\nsystemd-udevd.service\ntuned.service\nwaagent.service
STDERR: None
2025-04-23 05:05:27,699 - INFO - [likitha] [shutdown] [10.4.0.13] - Executing shutdown on 10.4.0.13
2025-04-23 05:05:27,924 - INFO - [likitha] [shutdown] [10.4.0.13] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-23 05:05:27,924 - ERROR - [likitha] [shutdown] [10.4.0.13] - Command failed: shutdown on 10.4.0.13 - name 'stdout_output' is not defined
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/working-appV3.py", line 501, in run_command
    artifact_data += f"\nCommand: {cmd}\n{stdout_output}\n"
NameError: name 'stdout_output' is not defined
2025-04-23 05:05:30,340 - ERROR - [likitha] [shutdown] [10.4.0.46] - Connection failed: 10.4.0.46
2025-04-23 05:07:11,731 - INFO - [likitha] [shutdown] [10.4.0.13] - Executing shutdown on 10.4.0.13
2025-04-23 05:07:11,956 - INFO - [likitha] [shutdown] [10.4.0.13] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-23 05:07:11,956 - ERROR - [likitha] [shutdown] [10.4.0.13] - Command failed: shutdown on 10.4.0.13 - too many values to unpack (expected 3)
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/working-appV3.py", line 499, in run_command
    stdout_output, stderr_output, exit_code = log_command(ssh, cmd, username, ip, action)
ValueError: too many values to unpack (expected 3)
2025-04-23 05:07:14,340 - ERROR - [likitha] [shutdown] [10.4.0.46] - Connection failed: 10.4.0.46
2025-04-23 07:53:04,732 - INFO - [likitha] [server_create] [10.2.5.6] - Server created: 10.2.5.6
2025-04-23 07:53:15,368 - INFO - [likitha] [bulk_upload] [10.5.6.3] - Bulk upload: 1 servers added
2025-04-23 07:53:25,509 - INFO - [likitha] [bulk_delete] [10.2.5.6] - Bulk delete: 1 servers
2025-04-23 07:53:32,900 - INFO - [likitha] [bulk_delete] [10.5.6.3] - Bulk delete: 1 servers
2025-04-23 07:53:40,634 - INFO - [likitha] [server_create] [10.5.6.9] - Server created: 10.5.6.9
2025-04-23 07:53:53,655 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: grep '^cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage}'
Exit code: 0
STDOUT: 0.687503
STDERR: None
2025-04-23 07:53:53,723 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: awk '/MemTotal/ {total=$2} /MemAvailable/ {avail=$2} END {print (total-avail)/total*100}' /proc/meminfo
Exit code: 0
STDOUT: 39.4064
STDERR: None
2025-04-23 07:53:53,787 - INFO - [] [os_detection] [] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-23 07:53:53,787 - INFO - [likitha] [compliance_check] [10.4.0.13] - Compliance check OS detection: centos
2025-04-23 07:53:57,181 - INFO - [likitha] [compliance_check] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 07:53:57,247 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: [ -f /var/run/reboot-required ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: None
2025-04-23 07:53:57,484 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: needs-restarting -r &>/dev/null; echo $?
Exit code: 0
STDOUT: 0
STDERR: None
2025-04-23 07:53:57,550 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: [ -f /var/run/reboot-needed ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: None
2025-04-23 07:53:57,620 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: df -h | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: None
2025-04-23 07:53:57,687 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: df -i | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: None
2025-04-23 07:53:57,754 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: cat /proc/loadavg | awk '{print $1, $2, $3}'
Exit code: 0
STDOUT: 0.08 0.03 0.05
STDERR: None
2025-04-23 07:53:57,833 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: sudo ufw status | grep 'Status: active'
Exit code: 1
STDOUT: None
STDERR: sudo: ufw: command not found
2025-04-23 07:53:57,922 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: sudo sshd -t
Exit code: 0
STDOUT: None
STDERR: None
2025-04-23 07:53:57,989 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: cat /proc/uptime | awk '{print $1}'
Exit code: 0
STDOUT: 10474.71
STDERR: None
2025-04-23 07:53:58,055 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: uname -r
Exit code: 0
STDOUT: 3.10.0-1160.119.1.el7.x86_64
STDERR: None
2025-04-23 07:53:58,175 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: timedatectl | grep 'System clock synchronized'
Exit code: 1
STDOUT: None
STDERR: None
2025-04-23 07:53:58,275 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: sudo diff <(cat /etc/fstab | grep -v '^#') <(df -h | awk '{print $1}')
Exit code: 2
STDOUT: None
STDERR: diff: /dev/fd/63: No such file or directory\ndiff: /dev/fd/62: No such file or directory
2025-04-23 07:53:58,341 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: getenforce
Exit code: 127
STDOUT: None
STDERR: bash: getenforce: command not found
2025-04-23 07:54:22,920 - INFO - [likitha] [health_check] [10.4.0.46, 10.4.0.13, 10.5.6.9] - Action COMPLETED - health_check on 3 servers
2025-04-23 07:55:49,849 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: grep '^cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage}'
Exit code: 0
STDOUT: 0.697531
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 07:55:49,904 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: awk '/MemTotal/ {total=$2} /MemAvailable/ {avail=$2} END {print (total-avail)/total*100}' /proc/meminfo
Exit code: 0
STDOUT: 39.6397
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 07:55:49,959 - INFO - [] [os_detection] [] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 07:55:49,960 - INFO - [sushrut] [compliance_check] [10.4.0.13] - Compliance check OS detection: centos
2025-04-23 07:55:50,727 - INFO - [sushrut] [compliance_check] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 07:55:50,781 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: [ -f /var/run/reboot-required ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 07:55:51,021 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: needs-restarting -r &>/dev/null; echo $?
Exit code: 0
STDOUT: 0
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 07:55:51,074 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: [ -f /var/run/reboot-needed ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 07:55:51,133 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: df -h | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 07:55:51,189 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: df -i | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 07:55:51,244 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: cat /proc/loadavg | awk '{print $1, $2, $3}'
Exit code: 0
STDOUT: 0.09 0.04 0.05
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 07:55:51,312 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: sudo ufw status | grep 'Status: active'
Exit code: 1
STDOUT: None
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied\nsudo: ufw: command not found
2025-04-23 07:55:51,393 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: sudo sshd -t
Exit code: 0
STDOUT: None
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 07:55:51,448 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: cat /proc/uptime | awk '{print $1}'
Exit code: 0
STDOUT: 10588.17
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 07:55:51,501 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: uname -r
Exit code: 0
STDOUT: 3.10.0-1160.119.1.el7.x86_64
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 07:55:51,603 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: timedatectl | grep 'System clock synchronized'
Exit code: 1
STDOUT: None
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied
2025-04-23 07:55:51,693 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: sudo diff <(cat /etc/fstab | grep -v '^#') <(df -h | awk '{print $1}')
Exit code: 2
STDOUT: None
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied\ndiff: /dev/fd/63: No such file or directory\ndiff: /dev/fd/62: No such file or directory
2025-04-23 07:55:51,745 - INFO - [sushrut] [health_check] [10.4.0.13] - Command executed: getenforce
Exit code: 127
STDOUT: None
STDERR: Could not chdir to home directory /home/sushrut: Permission denied\nbash: /home/sushrut/.bashrc: Permission denied\nbash: getenforce: command not found
2025-04-23 07:56:19,206 - INFO - [sushrut] [health_check] [10.4.0.46, 10.4.0.13, 10.5.6.9] - Action COMPLETED - health_check on 3 servers
2025-04-23 07:56:46,029 - INFO - [] [os_detection] [] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-23 07:56:46,030 - INFO - [likitha] [patch_update] [10.4.0.13] - Patch check on 10.4.0.13
2025-04-23 07:56:48,356 - ERROR - [likitha] [patch_update] [10.4.0.46] - Patch operation failed on 10.4.0.46 - [Errno None] Unable to connect to port 22 on 10.4.0.46
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 409, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 10.4.0.46
2025-04-23 07:57:00,297 - ERROR - [likitha] [patch_update] [10.5.6.9] - Patch operation failed on 10.5.6.9 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-23 07:57:02,367 - INFO - [likitha] [patch_update] [10.4.0.13] - Command executed: sudo yum clean all && sudo yum makecache
Exit code: 0
STDOUT: Loaded plugins: langpacks\nCleaning repos: base-openlogic extras-openlogic updates-openlogic base extras\n              : openlogic updates\nLoaded plugins: langpacks\nMetadata Cache Created
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 07:57:05,675 - INFO - [likitha] [patch_update] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 07:57:39,666 - INFO - [likitha] [shutdown] [10.4.0.13] - Executing shutdown on 10.4.0.13
2025-04-23 07:57:39,904 - INFO - [likitha] [shutdown] [10.4.0.13] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-23 07:57:39,970 - INFO - [likitha] [shutdown] [10.4.0.13] - Command executed: date
Exit code: 0
STDOUT: Wed Apr 23 07:57:39 UTC 2025
STDERR: None
2025-04-23 07:57:40,038 - INFO - [likitha] [shutdown] [10.4.0.13] - Command executed: uptime -p
Exit code: 0
STDOUT: up 2 hours, 58 minutes
STDERR: None
2025-04-23 07:57:40,104 - INFO - [likitha] [shutdown] [10.4.0.13] - Command executed: free -h
Exit code: 0
STDOUT: total        used        free      shared  buff/cache   available\nMem:           925M        217M        125M        6.2M        583M        555M\nSwap:            0B          0B          0B
STDERR: None
2025-04-23 07:57:40,172 - INFO - [likitha] [shutdown] [10.4.0.13] - Command executed: df -h
Exit code: 0
STDOUT: Filesystem      Size  Used Avail Use% Mounted on\ndevtmpfs        453M     0  453M   0% /dev\ntmpfs           463M     0  463M   0% /dev/shm\ntmpfs           463M  6.2M  457M   2% /run\ntmpfs           463M     0  463M   0% /sys/fs/cgroup\n/dev/sda2        30G  2.4G   27G   8% /\n/dev/sda1       494M   92M  403M  19% /boot\n/dev/sda15      495M   12M  484M   3% /boot/efi\n/dev/sdb1       3.9G   16M  3.7G   1% /mnt/resource\ntmpfs            93M     0   93M   0% /run/user/1152801110
STDERR: None
2025-04-23 07:57:40,361 - INFO - [likitha] [shutdown] [10.4.0.13] - Command executed: sudo shutdown -h now
Exit code: -1
STDOUT: None
STDERR: None
2025-04-23 07:57:42,244 - ERROR - [likitha] [shutdown] [10.4.0.46] - Connection failed: 10.4.0.46
2025-04-23 07:57:54,203 - ERROR - [likitha] [shutdown] [10.5.6.9] - Command failed: shutdown on 10.5.6.9 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 482, in run_command
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-23 07:59:36,420 - ERROR - [likitha] [reboot] [10.4.0.46] - Connection failed: 10.4.0.46
2025-04-23 07:59:48,376 - ERROR - [likitha] [reboot] [10.4.0.13] - Command failed: reboot on 10.4.0.13 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 482, in run_command
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-23 07:59:48,376 - ERROR - [likitha] [reboot] [10.5.6.9] - Command failed: reboot on 10.5.6.9 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 482, in run_command
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-23 08:01:54,211 - INFO - [likitha] [reboot] [10.4.0.13] - Executing reboot on 10.4.0.13
2025-04-23 08:01:54,453 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-23 08:01:54,518 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: date
Exit code: 0
STDOUT: Wed Apr 23 08:01:54 UTC 2025
STDERR: None
2025-04-23 08:01:54,585 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: uptime -p
Exit code: 0
STDOUT: up 2 minutes
STDERR: None
2025-04-23 08:01:54,653 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: free -h
Exit code: 0
STDOUT: total        used        free      shared  buff/cache   available\nMem:           925M        203M        553M        6.2M        169M        581M\nSwap:            0B          0B          0B
STDERR: None
2025-04-23 08:01:54,721 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: df -h
Exit code: 0
STDOUT: Filesystem      Size  Used Avail Use% Mounted on\ndevtmpfs        453M     0  453M   0% /dev\ntmpfs           463M     0  463M   0% /dev/shm\ntmpfs           463M  6.2M  457M   2% /run\ntmpfs           463M     0  463M   0% /sys/fs/cgroup\n/dev/sda2        30G  2.4G   27G   8% /\n/dev/sda1       494M   92M  403M  19% /boot\n/dev/sda15      495M   12M  484M   3% /boot/efi\n/dev/sdb1       3.9G   16M  3.7G   1% /mnt/resource\ntmpfs            93M     0   93M   0% /run/user/1152801110
STDERR: None
2025-04-23 08:01:54,804 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: systemctl list-units --type=service --state=running --no-legend | awk '{print $1}'
Exit code: 0
STDOUT: atd.service\nauditd.service\nchronyd.service\ncrond.service\ndbus.service\ngetty@tty1.service\nhypervkvpd.service\nlibstoragemgmt.service\nlvm2-lvmetad.service\nNetworkManager.service\noddjobd.service\npolkit.service\npostfix.service\nrngd.service\nrpcbind.service\nrsyslog.service\nserial-getty@ttyS0.service\nsmartd.service\nsshd.service\nsssd.service\nsystemd-journald.service\nsystemd-logind.service\nsystemd-udevd.service\ntuned.service\nwaagent.service
STDERR: None
2025-04-23 08:01:54,962 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: sudo shutdown -r now
Exit code: -1
STDOUT: None
STDERR: None
2025-04-23 08:01:56,772 - ERROR - [likitha] [reboot] [10.4.0.46] - Connection failed: 10.4.0.46
2025-04-23 08:02:08,720 - ERROR - [likitha] [reboot] [10.5.6.9] - Command failed: reboot on 10.5.6.9 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 482, in run_command
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-23 08:04:55,770 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: uptime -p || uptime
Exit code: 0
STDOUT: up 2 minutes
STDERR: None
2025-04-23 08:04:55,853 - INFO - [likitha] [reboot] [10.4.0.13] - Command executed: systemctl list-units --type=service --state=running --no-legend | awk '{print $1}'
Exit code: 0
STDOUT: atd.service\nauditd.service\nchronyd.service\ncrond.service\ndbus.service\ngetty@tty1.service\nhypervkvpd.service\nlibstoragemgmt.service\nlvm2-lvmetad.service\nNetworkManager.service\noddjobd.service\npolkit.service\npostfix.service\nrngd.service\nrpcbind.service\nrsyslog.service\nserial-getty@ttyS0.service\nsmartd.service\nsshd.service\nsssd.service\nsystemd-journald.service\nsystemd-logind.service\nsystemd-udevd.service\ntuned.service\nwaagent.service
STDERR: None
2025-04-23 08:11:00,133 - INFO - [] [os_detection] [] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-23 08:11:00,133 - INFO - [likitha] [patch_update] [10.4.0.13] - Patch check on 10.4.0.13
2025-04-23 08:11:02,500 - ERROR - [likitha] [patch_update] [10.4.0.46] - Patch operation failed on 10.4.0.46 - [Errno None] Unable to connect to port 22 on 10.4.0.46
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 409, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 10.4.0.46
2025-04-23 08:11:14,449 - ERROR - [likitha] [patch_update] [10.5.6.9] - Patch operation failed on 10.5.6.9 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-23 08:11:16,215 - INFO - [likitha] [patch_update] [10.4.0.13] - Command executed: sudo yum clean all && sudo yum makecache
Exit code: 0
STDOUT: Loaded plugins: langpacks\nCleaning repos: base-openlogic extras-openlogic updates-openlogic base extras\n              : openlogic updates\nLoaded plugins: langpacks\nMetadata Cache Created
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 08:11:19,128 - INFO - [likitha] [patch_update] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 08:12:43,302 - INFO - [] [os_detection] [] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-23 08:12:43,303 - INFO - [likitha] [patch_update] [10.4.0.13] - Patch check on 10.4.0.13
2025-04-23 08:12:45,668 - ERROR - [likitha] [patch_update] [10.4.0.46] - Patch operation failed on 10.4.0.46 - [Errno None] Unable to connect to port 22 on 10.4.0.46
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 409, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 10.4.0.46
2025-04-23 08:12:57,624 - ERROR - [likitha] [patch_update] [10.5.6.9] - Patch operation failed on 10.5.6.9 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-23 08:12:58,601 - INFO - [likitha] [patch_update] [10.4.0.13] - Command executed: sudo yum clean all && sudo yum makecache
Exit code: 0
STDOUT: Loaded plugins: langpacks\nCleaning repos: base-openlogic extras-openlogic updates-openlogic base extras\n              : openlogic updates\nLoaded plugins: langpacks\nMetadata Cache Created
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 08:13:00,837 - INFO - [likitha] [patch_update] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 08:15:33,123 - INFO - [] [os_detection] [] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-23 08:15:33,123 - INFO - [likitha] [patch_update] [10.4.0.13] - Patch apply on 10.4.0.13
2025-04-23 08:15:35,460 - ERROR - [likitha] [patch_update] [10.4.0.46] - Patch operation failed on 10.4.0.46 - [Errno None] Unable to connect to port 22 on 10.4.0.46
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 409, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 10.4.0.46
2025-04-23 08:15:47,393 - ERROR - [likitha] [patch_update] [10.5.6.9] - Patch operation failed on 10.5.6.9 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-23 08:15:51,079 - INFO - [likitha] [patch_update] [10.4.0.13] - Command executed: sudo yum clean all && sudo yum makecache
Exit code: 0
STDOUT: Loaded plugins: langpacks\nCleaning repos: base-openlogic extras-openlogic updates-openlogic base extras\n              : openlogic updates\nLoaded plugins: langpacks\nMetadata Cache Created
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 08:15:54,243 - INFO - [likitha] [patch_update] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 08:19:27,891 - INFO - [] [os_detection] [] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-23 08:19:27,892 - INFO - [likitha] [patch_update] [10.4.0.13] - Patch apply on 10.4.0.13
2025-04-23 08:19:30,212 - ERROR - [likitha] [patch_update] [10.4.0.46] - Patch operation failed on 10.4.0.46 - [Errno None] Unable to connect to port 22 on 10.4.0.46
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 409, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 10.4.0.46
2025-04-23 08:19:42,164 - ERROR - [likitha] [patch_update] [10.5.6.9] - Patch operation failed on 10.5.6.9 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-23 08:19:46,342 - INFO - [likitha] [patch_update] [10.4.0.13] - Command executed: sudo yum clean all && sudo yum makecache
Exit code: 0
STDOUT: Loaded plugins: langpacks\nCleaning repos: base-openlogic extras-openlogic updates-openlogic base extras\n              : openlogic updates\nLoaded plugins: langpacks\nMetadata Cache Created
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 08:19:49,096 - INFO - [likitha] [patch_update] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 08:19:49,814 - INFO - [] [os_detection] [] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-23 08:19:50,085 - INFO - [likitha] [patch_and_reboot] [10.4.0.13] - Command executed: needs-restarting -r &> /dev/null; echo $?
Exit code: 0
STDOUT: 0
STDERR: None
2025-04-23 08:21:11,596 - INFO - [] [os_detection] [] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-23 08:21:11,597 - INFO - [likitha] [patch_update] [10.4.0.13] - Patch check on 10.4.0.13
2025-04-23 08:21:13,956 - ERROR - [likitha] [patch_update] [10.4.0.46] - Patch operation failed on 10.4.0.46 - [Errno None] Unable to connect to port 22 on 10.4.0.46
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 409, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 10.4.0.46
2025-04-23 08:21:25,922 - ERROR - [likitha] [patch_update] [10.5.6.9] - Patch operation failed on 10.5.6.9 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-23 08:21:28,947 - INFO - [likitha] [patch_update] [10.4.0.13] - Command executed: sudo yum clean all && sudo yum makecache
Exit code: 0
STDOUT: Loaded plugins: langpacks\nCleaning repos: base-openlogic extras-openlogic updates-openlogic base extras\n              : openlogic updates\nLoaded plugins: langpacks\nMetadata Cache Created
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 08:21:31,796 - INFO - [likitha] [patch_update] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 08:24:38,701 - INFO - [] [os_detection] [] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-23 08:24:38,702 - INFO - [likitha] [patch_update] [10.4.0.13] - Patch check on 10.4.0.13
2025-04-23 08:24:41,060 - ERROR - [likitha] [patch_update] [10.4.0.46] - Patch operation failed on 10.4.0.46 - [Errno None] Unable to connect to port 22 on 10.4.0.46
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 409, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 10.4.0.46
2025-04-23 08:24:52,971 - ERROR - [likitha] [patch_update] [10.5.6.9] - Patch operation failed on 10.5.6.9 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-23 08:24:55,787 - INFO - [likitha] [patch_update] [10.4.0.13] - Command executed: sudo yum clean all && sudo yum makecache
Exit code: 0
STDOUT: Loaded plugins: langpacks\nCleaning repos: base-openlogic extras-openlogic updates-openlogic base extras\n              : openlogic updates\nLoaded plugins: langpacks\nMetadata Cache Created
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 08:24:58,499 - INFO - [likitha] [patch_update] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 08:26:31,771 - INFO - [] [os_detection] [] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-23 08:26:31,772 - INFO - [likitha] [patch_update] [10.4.0.13] - Patch check on 10.4.0.13
2025-04-23 08:26:34,148 - ERROR - [likitha] [patch_update] [10.4.0.46] - Patch operation failed on 10.4.0.46 - [Errno None] Unable to connect to port 22 on 10.4.0.46
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 409, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 10.4.0.46
2025-04-23 08:26:46,066 - ERROR - [likitha] [patch_update] [10.5.6.9] - Patch operation failed on 10.5.6.9 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-23 08:26:47,889 - INFO - [likitha] [patch_update] [10.4.0.13] - Command executed: sudo yum clean all && sudo yum makecache
Exit code: 0
STDOUT: Loaded plugins: langpacks\nCleaning repos: base-openlogic extras-openlogic updates-openlogic base extras\n              : openlogic updates\nLoaded plugins: langpacks\nMetadata Cache Created
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 08:26:50,830 - INFO - [likitha] [patch_update] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 08:27:47,941 - INFO - [] [os_detection] [] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-23 08:27:47,941 - INFO - [likitha] [patch_update] [10.4.0.13] - Patch check on 10.4.0.13
2025-04-23 08:27:50,308 - ERROR - [likitha] [patch_update] [10.4.0.46] - Patch operation failed on 10.4.0.46 - [Errno None] Unable to connect to port 22 on 10.4.0.46
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 409, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 10.4.0.46
2025-04-23 08:28:02,228 - ERROR - [likitha] [patch_update] [10.5.6.9] - Patch operation failed on 10.5.6.9 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-23 08:28:04,069 - INFO - [likitha] [patch_update] [10.4.0.13] - Command executed: sudo yum clean all && sudo yum makecache
Exit code: 0
STDOUT: Loaded plugins: langpacks\nCleaning repos: base-openlogic extras-openlogic updates-openlogic base extras\n              : openlogic updates\nLoaded plugins: langpacks\nMetadata Cache Created
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 08:28:06,788 - INFO - [likitha] [patch_update] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 08:30:52,499 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: grep '^cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage}'
Exit code: 0
STDOUT: 10.0456
STDERR: None
2025-04-23 08:30:52,563 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: awk '/MemTotal/ {total=$2} /MemAvailable/ {avail=$2} END {print (total-avail)/total*100}' /proc/meminfo
Exit code: 0
STDOUT: 36.7289
STDERR: None
2025-04-23 08:30:52,629 - INFO - [] [os_detection] [] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-23 08:30:52,630 - INFO - [likitha] [compliance_check] [10.4.0.13] - Compliance check OS detection: centos
2025-04-23 08:30:53,876 - INFO - [likitha] [compliance_check] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 08:30:53,941 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: [ -f /var/run/reboot-required ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: None
2025-04-23 08:30:54,179 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: needs-restarting -r &>/dev/null; echo $?
Exit code: 0
STDOUT: 0
STDERR: None
2025-04-23 08:30:54,243 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: [ -f /var/run/reboot-needed ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: None
2025-04-23 08:30:54,314 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: df -h | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: None
2025-04-23 08:30:54,381 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: df -i | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: None
2025-04-23 08:30:54,447 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: cat /proc/loadavg | awk '{print $1, $2, $3}'
Exit code: 0
STDOUT: 0.10 0.15 0.15
STDERR: None
2025-04-23 08:30:54,526 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: sudo ufw status | grep 'Status: active'
Exit code: 1
STDOUT: None
STDERR: sudo: ufw: command not found
2025-04-23 08:30:54,615 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: sudo sshd -t
Exit code: 0
STDOUT: None
STDERR: None
2025-04-23 08:30:54,681 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: cat /proc/uptime | awk '{print $1}'
Exit code: 0
STDOUT: 1731.38
STDERR: None
2025-04-23 08:30:54,747 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: uname -r
Exit code: 0
STDOUT: 3.10.0-1160.119.1.el7.x86_64
STDERR: None
2025-04-23 08:30:54,876 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: timedatectl | grep 'System clock synchronized'
Exit code: 1
STDOUT: None
STDERR: None
2025-04-23 08:30:54,975 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: sudo diff <(cat /etc/fstab | grep -v '^#') <(df -h | awk '{print $1}')
Exit code: 2
STDOUT: None
STDERR: diff: /dev/fd/63: No such file or directory\ndiff: /dev/fd/62: No such file or directory
2025-04-23 08:30:55,038 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: getenforce
Exit code: 127
STDOUT: None
STDERR: bash: getenforce: command not found
2025-04-23 08:31:21,811 - INFO - [likitha] [health_check] [10.4.0.46, 10.4.0.13, 10.5.6.9] - Action COMPLETED - health_check on 3 servers
2025-04-23 08:32:38,356 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: grep '^cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage}'
Exit code: 0
STDOUT: 9.55985
STDERR: None
2025-04-23 08:32:38,421 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: awk '/MemTotal/ {total=$2} /MemAvailable/ {avail=$2} END {print (total-avail)/total*100}' /proc/meminfo
Exit code: 0
STDOUT: 36.7087
STDERR: None
2025-04-23 08:32:38,485 - INFO - [] [os_detection] [] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-23 08:32:38,485 - INFO - [likitha] [compliance_check] [10.4.0.13] - Compliance check OS detection: centos
2025-04-23 08:32:39,249 - INFO - [likitha] [compliance_check] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 08:32:39,314 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: [ -f /var/run/reboot-required ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: None
2025-04-23 08:32:39,547 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: needs-restarting -r &>/dev/null; echo $?
Exit code: 0
STDOUT: 0
STDERR: None
2025-04-23 08:32:39,613 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: [ -f /var/run/reboot-needed ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: None
2025-04-23 08:32:39,681 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: df -h | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: None
2025-04-23 08:32:39,747 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: df -i | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: None
2025-04-23 08:32:39,812 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: cat /proc/loadavg | awk '{print $1, $2, $3}'
Exit code: 0
STDOUT: 0.26 0.16 0.15
STDERR: None
2025-04-23 08:32:39,890 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: sudo ufw status | grep 'Status: active'
Exit code: 1
STDOUT: None
STDERR: sudo: ufw: command not found
2025-04-23 08:32:39,979 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: sudo sshd -t
Exit code: 0
STDOUT: None
STDERR: None
2025-04-23 08:32:40,054 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: cat /proc/uptime | awk '{print $1}'
Exit code: 0
STDOUT: 1836.75
STDERR: None
2025-04-23 08:32:40,118 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: uname -r
Exit code: 0
STDOUT: 3.10.0-1160.119.1.el7.x86_64
STDERR: None
2025-04-23 08:32:40,232 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: timedatectl | grep 'System clock synchronized'
Exit code: 1
STDOUT: None
STDERR: None
2025-04-23 08:32:40,328 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: sudo diff <(cat /etc/fstab | grep -v '^#') <(df -h | awk '{print $1}')
Exit code: 2
STDOUT: None
STDERR: diff: /dev/fd/63: No such file or directory\ndiff: /dev/fd/62: No such file or directory
2025-04-23 08:32:40,392 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: getenforce
Exit code: 127
STDOUT: None
STDERR: bash: getenforce: command not found
2025-04-23 08:33:07,624 - INFO - [likitha] [health_check] [10.4.0.46, 10.4.0.13, 10.5.6.9] - Action COMPLETED - health_check on 3 servers
2025-04-23 10:20:21,526 - INFO - [likitha] [server_create] [10.4.0.18] - Server created: 10.4.0.18
2025-04-23 10:20:34,433 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: grep '^cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage}'
Exit code: 0
STDOUT: 2.32466
STDERR: None
2025-04-23 10:20:34,498 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: awk '/MemTotal/ {total=$2} /MemAvailable/ {avail=$2} END {print (total-avail)/total*100}' /proc/meminfo
Exit code: 0
STDOUT: 37.6587
STDERR: None
2025-04-23 10:20:34,563 - INFO - [] [os_detection] [] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-23 10:20:34,563 - INFO - [likitha] [compliance_check] [10.4.0.13] - Compliance check OS detection: centos
2025-04-23 10:20:34,582 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: grep '^cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage}'
Exit code: 0
STDOUT: 1.80555
STDERR: None
2025-04-23 10:20:34,648 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: awk '/MemTotal/ {total=$2} /MemAvailable/ {avail=$2} END {print (total-avail)/total*100}' /proc/meminfo
Exit code: 0
STDOUT: 41.2775
STDERR: None
2025-04-23 10:20:34,713 - INFO - [] [os_detection] [] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-23 10:20:34,713 - INFO - [likitha] [compliance_check] [10.4.0.18] - Compliance check OS detection: centos
2025-04-23 10:20:35,446 - INFO - [likitha] [compliance_check] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 10:20:35,514 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: [ -f /var/run/reboot-required ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: None
2025-04-23 10:20:35,748 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: needs-restarting -r &>/dev/null; echo $?
Exit code: 0
STDOUT: 0
STDERR: None
2025-04-23 10:20:35,811 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: [ -f /var/run/reboot-needed ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: None
2025-04-23 10:20:35,878 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: df -h | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: None
2025-04-23 10:20:35,944 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: df -i | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: None
2025-04-23 10:20:36,010 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: cat /proc/loadavg | awk '{print $1, $2, $3}'
Exit code: 0
STDOUT: 0.00 0.01 0.05
STDERR: None
2025-04-23 10:20:36,088 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: sudo ufw status | grep 'Status: active'
Exit code: 1
STDOUT: None
STDERR: sudo: ufw: command not found
2025-04-23 10:20:36,178 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: sudo sshd -t
Exit code: 0
STDOUT: None
STDERR: None
2025-04-23 10:20:36,244 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: cat /proc/uptime | awk '{print $1}'
Exit code: 0
STDOUT: 8312.94
STDERR: None
2025-04-23 10:20:36,308 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: uname -r
Exit code: 0
STDOUT: 3.10.0-1160.119.1.el7.x86_64
STDERR: None
2025-04-23 10:20:36,421 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: timedatectl | grep 'System clock synchronized'
Exit code: 1
STDOUT: None
STDERR: None
2025-04-23 10:20:36,519 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: sudo diff <(cat /etc/fstab | grep -v '^#') <(df -h | awk '{print $1}')
Exit code: 2
STDOUT: None
STDERR: diff: /dev/fd/63: No such file or directory\ndiff: /dev/fd/62: No such file or directory
2025-04-23 10:20:36,583 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: getenforce
Exit code: 127
STDOUT: None
STDERR: bash: getenforce: command not found
2025-04-23 10:20:37,622 - INFO - [likitha] [compliance_check] [10.4.0.18] - Command executed: sudo yum check-update
Exit code: 1
STDOUT: None
STDERR: We trust you have received the usual lecture from the local System\nAdministrator. It usually boils down to these three things:\n\n    #1) Respect the privacy of others.\n    #2) Think before you type.\n    #3) With great power comes great responsibility.\n\nsudo: no tty present and no askpass program specified
2025-04-23 10:20:37,701 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: [ -f /var/run/reboot-required ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: None
2025-04-23 10:20:38,012 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: needs-restarting -r &>/dev/null; echo $?
Exit code: 0
STDOUT: 0
STDERR: None
2025-04-23 10:20:38,097 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: [ -f /var/run/reboot-needed ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: None
2025-04-23 10:20:38,171 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: df -h | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: None
2025-04-23 10:20:38,244 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: df -i | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: None
2025-04-23 10:20:38,311 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: cat /proc/loadavg | awk '{print $1, $2, $3}'
Exit code: 0
STDOUT: 0.00 0.01 0.05
STDERR: None
2025-04-23 10:20:40,473 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: sudo ufw status | grep 'Status: active'
Exit code: 1
STDOUT: None
STDERR: We trust you have received the usual lecture from the local System\nAdministrator. It usually boils down to these three things:\n\n    #1) Respect the privacy of others.\n    #2) Think before you type.\n    #3) With great power comes great responsibility.\n\nsudo: no tty present and no askpass program specified
2025-04-23 10:20:42,211 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: sudo sshd -t
Exit code: 1
STDOUT: None
STDERR: We trust you have received the usual lecture from the local System\nAdministrator. It usually boils down to these three things:\n\n    #1) Respect the privacy of others.\n    #2) Think before you type.\n    #3) With great power comes great responsibility.\n\nsudo: no tty present and no askpass program specified
2025-04-23 10:20:42,275 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: cat /proc/uptime | awk '{print $1}'
Exit code: 0
STDOUT: 5832.25
STDERR: None
2025-04-23 10:20:42,339 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: uname -r
Exit code: 0
STDOUT: 3.10.0-1160.83.1.el7.x86_64
STDERR: None
2025-04-23 10:20:42,546 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: timedatectl | grep 'System clock synchronized'
Exit code: 1
STDOUT: None
STDERR: None
2025-04-23 10:20:45,232 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: sudo diff <(cat /etc/fstab | grep -v '^#') <(df -h | awk '{print $1}')
Exit code: 1
STDOUT: None
STDERR: We trust you have received the usual lecture from the local System\nAdministrator. It usually boils down to these three things:\n\n    #1) Respect the privacy of others.\n    #2) Think before you type.\n    #3) With great power comes great responsibility.\n\nsudo: no tty present and no askpass program specified
2025-04-23 10:20:45,300 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: getenforce
Exit code: 127
STDOUT: None
STDERR: bash: getenforce: command not found
2025-04-23 10:21:03,554 - INFO - [likitha] [health_check] [10.4.0.18, 10.4.0.46, 10.4.0.13, 10.5.6.9] - Action COMPLETED - health_check on 4 servers
2025-04-23 11:09:54,253 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: grep '^cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage}'
Exit code: 0
STDOUT: 1.80215
STDERR: None
2025-04-23 11:09:54,320 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: awk '/MemTotal/ {total=$2} /MemAvailable/ {avail=$2} END {print (total-avail)/total*100}' /proc/meminfo
Exit code: 0
STDOUT: 37.7603
STDERR: None
2025-04-23 11:09:54,361 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: grep '^cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage}'
Exit code: 0
STDOUT: 1.32489
STDERR: None
2025-04-23 11:09:54,384 - INFO - [] [os_detection] [] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-23 11:09:54,384 - INFO - [likitha] [compliance_check] [10.4.0.13] - Compliance check OS detection: centos
2025-04-23 11:09:54,426 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: awk '/MemTotal/ {total=$2} /MemAvailable/ {avail=$2} END {print (total-avail)/total*100}' /proc/meminfo
Exit code: 0
STDOUT: 41.2999
STDERR: None
2025-04-23 11:09:54,490 - INFO - [] [os_detection] [] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-23 11:09:54,491 - INFO - [likitha] [compliance_check] [10.4.0.18] - Compliance check OS detection: centos
2025-04-23 11:09:55,177 - INFO - [likitha] [compliance_check] [10.4.0.13] - Command executed: sudo yum check-update
Exit code: 0
STDOUT: Loaded plugins: langpacks
STDERR: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"\nCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was\n14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
2025-04-23 11:09:55,240 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: [ -f /var/run/reboot-required ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: None
2025-04-23 11:09:55,483 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: needs-restarting -r &>/dev/null; echo $?
Exit code: 0
STDOUT: 0
STDERR: None
2025-04-23 11:09:55,548 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: [ -f /var/run/reboot-needed ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: None
2025-04-23 11:09:55,617 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: df -h | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: None
2025-04-23 11:09:55,683 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: df -i | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: None
2025-04-23 11:09:55,749 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: cat /proc/loadavg | awk '{print $1, $2, $3}'
Exit code: 0
STDOUT: 0.08 0.04 0.05
STDERR: None
2025-04-23 11:09:55,827 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: sudo ufw status | grep 'Status: active'
Exit code: 1
STDOUT: None
STDERR: sudo: ufw: command not found
2025-04-23 11:09:55,917 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: sudo sshd -t
Exit code: 0
STDOUT: None
STDERR: None
2025-04-23 11:09:55,982 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: cat /proc/uptime | awk '{print $1}'
Exit code: 0
STDOUT: 11272.68
STDERR: None
2025-04-23 11:09:56,047 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: uname -r
Exit code: 0
STDOUT: 3.10.0-1160.119.1.el7.x86_64
STDERR: None
2025-04-23 11:09:56,158 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: timedatectl | grep 'System clock synchronized'
Exit code: 1
STDOUT: None
STDERR: None
2025-04-23 11:09:56,255 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: sudo diff <(cat /etc/fstab | grep -v '^#') <(df -h | awk '{print $1}')
Exit code: 2
STDOUT: None
STDERR: diff: /dev/fd/63: No such file or directory\ndiff: /dev/fd/62: No such file or directory
2025-04-23 11:09:56,319 - INFO - [likitha] [health_check] [10.4.0.13] - Command executed: getenforce
Exit code: 127
STDOUT: None
STDERR: bash: getenforce: command not found
2025-04-23 11:09:57,130 - INFO - [likitha] [compliance_check] [10.4.0.18] - Command executed: sudo yum check-update
Exit code: 1
STDOUT: None
STDERR: We trust you have received the usual lecture from the local System\nAdministrator. It usually boils down to these three things:\n\n    #1) Respect the privacy of others.\n    #2) Think before you type.\n    #3) With great power comes great responsibility.\n\nsudo: no tty present and no askpass program specified
2025-04-23 11:09:57,229 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: [ -f /var/run/reboot-required ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: None
2025-04-23 11:09:57,478 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: needs-restarting -r &>/dev/null; echo $?
Exit code: 0
STDOUT: 0
STDERR: None
2025-04-23 11:09:57,545 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: [ -f /var/run/reboot-needed ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: None
2025-04-23 11:09:57,618 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: df -h | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: None
2025-04-23 11:09:57,685 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: df -i | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: None
2025-04-23 11:09:57,751 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: cat /proc/loadavg | awk '{print $1, $2, $3}'
Exit code: 0
STDOUT: 0.00 0.01 0.05
STDERR: None
2025-04-23 11:09:59,437 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: sudo ufw status | grep 'Status: active'
Exit code: 1
STDOUT: None
STDERR: We trust you have received the usual lecture from the local System\nAdministrator. It usually boils down to these three things:\n\n    #1) Respect the privacy of others.\n    #2) Think before you type.\n    #3) With great power comes great responsibility.\n\nsudo: no tty present and no askpass program specified
2025-04-23 11:10:01,728 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: sudo sshd -t
Exit code: 1
STDOUT: None
STDERR: We trust you have received the usual lecture from the local System\nAdministrator. It usually boils down to these three things:\n\n    #1) Respect the privacy of others.\n    #2) Think before you type.\n    #3) With great power comes great responsibility.\n\nsudo: no tty present and no askpass program specified
2025-04-23 11:10:01,798 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: cat /proc/uptime | awk '{print $1}'
Exit code: 0
STDOUT: 8791.77
STDERR: None
2025-04-23 11:10:01,864 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: uname -r
Exit code: 0
STDOUT: 3.10.0-1160.83.1.el7.x86_64
STDERR: None
2025-04-23 11:10:01,980 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: timedatectl | grep 'System clock synchronized'
Exit code: 1
STDOUT: None
STDERR: None
2025-04-23 11:10:04,024 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: sudo diff <(cat /etc/fstab | grep -v '^#') <(df -h | awk '{print $1}')
Exit code: 1
STDOUT: None
STDERR: We trust you have received the usual lecture from the local System\nAdministrator. It usually boils down to these three things:\n\n    #1) Respect the privacy of others.\n    #2) Think before you type.\n    #3) With great power comes great responsibility.\n\nsudo: no tty present and no askpass program specified
2025-04-23 11:10:04,089 - INFO - [likitha] [health_check] [10.4.0.18] - Command executed: getenforce
Exit code: 127
STDOUT: None
STDERR: bash: getenforce: command not found
2025-04-23 11:10:23,391 - INFO - [likitha] [health_check] [10.4.0.18, 10.4.0.46, 10.4.0.13, 10.5.6.9] - Action COMPLETED - health_check on 4 servers
2025-04-27 01:27:18,597 - ERROR - [anonymous] [http_error] [http://10.5.0.4:5002/favicon.ico] - HTTP 404 - GET /favicon.ico
2025-04-27 01:28:49,933 - ERROR - [likitha] [reboot] [10.4.0.46] - Command failed: reboot on 10.4.0.46 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 482, in run_command
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-27 01:28:49,933 - ERROR - [likitha] [reboot] [10.4.0.13] - Command failed: reboot on 10.4.0.13 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 482, in run_command
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-27 01:28:49,934 - ERROR - [likitha] [reboot] [10.5.6.9] - Command failed: reboot on 10.5.6.9 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 482, in run_command
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-27 01:28:49,935 - ERROR - [likitha] [reboot] [10.4.0.18] - Command failed: reboot on 10.4.0.18 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 482, in run_command
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-27 01:36:49,398 - INFO - [likitha] [bulk_delete] [10.4.0.18] - Bulk delete: 1 servers
2025-04-27 02:15:58,183 - INFO - [likitha] [server_create] [10.5.0.6] - Server created: 10.5.0.6
2025-04-27 02:16:03,993 - INFO - [likitha] [health_check] [10.5.0.6] - Command executed: grep '^cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage}'
Exit code: 0
STDOUT: 7.31803
STDERR: None
2025-04-27 02:16:04,055 - INFO - [likitha] [health_check] [10.5.0.6] - Command executed: awk '/MemTotal/ {total=$2} /MemAvailable/ {avail=$2} END {print (total-avail)/total*100}' /proc/meminfo
Exit code: 0
STDOUT: 41.8782
STDERR: None
2025-04-27 02:16:04,116 - INFO - [] [os_detection] [] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-27 02:16:04,117 - INFO - [likitha] [compliance_check] [10.5.0.6] - Compliance check OS detection: centos
2025-04-27 02:16:06,112 - INFO - [likitha] [compliance_check] [10.5.0.6] - Command executed: sudo yum check-update
Exit code: 1
STDOUT: None
STDERR: We trust you have received the usual lecture from the local System\nAdministrator. It usually boils down to these three things:\n\n    #1) Respect the privacy of others.\n    #2) Think before you type.\n    #3) With great power comes great responsibility.\n\nsudo: no tty present and no askpass program specified
2025-04-27 02:16:06,175 - INFO - [likitha] [health_check] [10.5.0.6] - Command executed: [ -f /var/run/reboot-required ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: None
2025-04-27 02:16:06,485 - INFO - [likitha] [health_check] [10.5.0.6] - Command executed: needs-restarting -r &>/dev/null; echo $?
Exit code: 0
STDOUT: 0
STDERR: None
2025-04-27 02:16:06,554 - INFO - [likitha] [health_check] [10.5.0.6] - Command executed: [ -f /var/run/reboot-needed ] && echo Yes || echo No
Exit code: 0
STDOUT: No
STDERR: None
2025-04-27 02:16:06,621 - INFO - [likitha] [health_check] [10.5.0.6] - Command executed: df -h | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: None
2025-04-27 02:16:06,685 - INFO - [likitha] [health_check] [10.5.0.6] - Command executed: df -i | awk '$5 > 80 {print $1}'
Exit code: 0
STDOUT: Filesystem
STDERR: None
2025-04-27 02:16:06,747 - INFO - [likitha] [health_check] [10.5.0.6] - Command executed: cat /proc/loadavg | awk '{print $1, $2, $3}'
Exit code: 0
STDOUT: 0.12 0.22 0.22
STDERR: None
2025-04-27 02:16:09,673 - INFO - [likitha] [health_check] [10.5.0.6] - Command executed: sudo ufw status | grep 'Status: active'
Exit code: 1
STDOUT: None
STDERR: We trust you have received the usual lecture from the local System\nAdministrator. It usually boils down to these three things:\n\n    #1) Respect the privacy of others.\n    #2) Think before you type.\n    #3) With great power comes great responsibility.\n\nsudo: no tty present and no askpass program specified
2025-04-27 02:16:11,652 - INFO - [likitha] [health_check] [10.5.0.6] - Command executed: sudo sshd -t
Exit code: 1
STDOUT: None
STDERR: We trust you have received the usual lecture from the local System\nAdministrator. It usually boils down to these three things:\n\n    #1) Respect the privacy of others.\n    #2) Think before you type.\n    #3) With great power comes great responsibility.\n\nsudo: no tty present and no askpass program specified
2025-04-27 02:16:11,713 - INFO - [likitha] [health_check] [10.5.0.6] - Command executed: cat /proc/uptime | awk '{print $1}'
Exit code: 0
STDOUT: 1267.32
STDERR: None
2025-04-27 02:16:11,775 - INFO - [likitha] [health_check] [10.5.0.6] - Command executed: uname -r
Exit code: 0
STDOUT: 3.10.0-1160.83.1.el7.x86_64
STDERR: None
2025-04-27 02:16:11,988 - INFO - [likitha] [health_check] [10.5.0.6] - Command executed: timedatectl | grep 'System clock synchronized'
Exit code: 1
STDOUT: None
STDERR: None
2025-04-27 02:16:14,391 - INFO - [likitha] [health_check] [10.5.0.6] - Command executed: sudo diff <(cat /etc/fstab | grep -v '^#') <(df -h | awk '{print $1}')
Exit code: 1
STDOUT: None
STDERR: We trust you have received the usual lecture from the local System\nAdministrator. It usually boils down to these three things:\n\n    #1) Respect the privacy of others.\n    #2) Think before you type.\n    #3) With great power comes great responsibility.\n\nsudo: no tty present and no askpass program specified
2025-04-27 02:16:14,454 - INFO - [likitha] [health_check] [10.5.0.6] - Command executed: getenforce
Exit code: 127
STDOUT: None
STDERR: bash: getenforce: command not found
2025-04-27 02:16:32,922 - INFO - [likitha] [health_check] [10.5.0.6, 10.4.0.46, 10.5.6.9, 10.4.0.13] - Action COMPLETED - health_check on 4 servers
2025-04-27 02:16:51,956 - INFO - [] [os_detection] [] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-27 02:16:51,956 - INFO - [likitha] [patch_update] [10.5.0.6] - Patch check on 10.5.0.6
2025-04-27 02:16:53,881 - INFO - [likitha] [patch_update] [10.5.0.6] - Command executed: sudo yum clean all && sudo yum makecache
Exit code: 1
STDOUT: None
STDERR: We trust you have received the usual lecture from the local System\nAdministrator. It usually boils down to these three things:\n\n    #1) Respect the privacy of others.\n    #2) Think before you type.\n    #3) With great power comes great responsibility.\n\nsudo: no tty present and no askpass program specified
2025-04-27 02:16:56,576 - INFO - [likitha] [patch_update] [10.5.0.6] - Command executed: sudo yum check-update
Exit code: 1
STDOUT: None
STDERR: We trust you have received the usual lecture from the local System\nAdministrator. It usually boils down to these three things:\n\n    #1) Respect the privacy of others.\n    #2) Think before you type.\n    #3) With great power comes great responsibility.\n\nsudo: no tty present and no askpass program specified
2025-04-27 02:17:06,135 - ERROR - [likitha] [patch_update] [10.4.0.46] - Patch operation failed on 10.4.0.46 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-27 02:17:06,135 - ERROR - [likitha] [patch_update] [10.5.6.9] - Patch operation failed on 10.5.6.9 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-27 02:17:06,138 - ERROR - [likitha] [patch_update] [10.4.0.13] - Patch operation failed on 10.4.0.13 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-27 02:29:46,689 - INFO - [] [os_detection] [] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-27 02:29:46,690 - INFO - [likitha] [patch_update] [10.5.0.6] - Patch check on 10.5.0.6
2025-04-27 02:29:48,873 - INFO - [likitha] [patch_update] [10.5.0.6] - Command executed: sudo yum clean all && sudo yum makecache
Exit code: 1
STDOUT: None
STDERR: We trust you have received the usual lecture from the local System\nAdministrator. It usually boils down to these three things:\n\n    #1) Respect the privacy of others.\n    #2) Think before you type.\n    #3) With great power comes great responsibility.\n\nsudo: no tty present and no askpass program specified
2025-04-27 02:29:51,626 - INFO - [likitha] [patch_update] [10.5.0.6] - Command executed: sudo yum check-update
Exit code: 1
STDOUT: None
STDERR: We trust you have received the usual lecture from the local System\nAdministrator. It usually boils down to these three things:\n\n    #1) Respect the privacy of others.\n    #2) Think before you type.\n    #3) With great power comes great responsibility.\n\nsudo: no tty present and no askpass program specified
2025-04-27 02:30:00,869 - ERROR - [likitha] [patch_update] [10.4.0.13] - Patch operation failed on 10.4.0.13 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-27 02:30:00,869 - ERROR - [likitha] [patch_update] [10.5.6.9] - Patch operation failed on 10.5.6.9 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-27 02:30:00,872 - ERROR - [likitha] [patch_update] [10.4.0.46] - Patch operation failed on 10.4.0.46 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-27 02:59:33,396 - INFO - [] [os_detection] [] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-27 02:59:33,397 - INFO - [likitha] [patch_update] [10.5.0.6] - Patch check on 10.5.0.6
2025-04-27 02:59:35,566 - INFO - [likitha] [patch_update] [10.5.0.6] - Command executed: sudo yum clean all && sudo yum makecache
Exit code: 1
STDOUT: None
STDERR: We trust you have received the usual lecture from the local System\nAdministrator. It usually boils down to these three things:\n\n    #1) Respect the privacy of others.\n    #2) Think before you type.\n    #3) With great power comes great responsibility.\n\nsudo: no tty present and no askpass program specified
2025-04-27 02:59:38,003 - INFO - [likitha] [patch_update] [10.5.0.6] - Command executed: sudo yum check-update -q
Exit code: 1
STDOUT: None
STDERR: We trust you have received the usual lecture from the local System\nAdministrator. It usually boils down to these three things:\n\n    #1) Respect the privacy of others.\n    #2) Think before you type.\n    #3) With great power comes great responsibility.\n\nsudo: no tty present and no askpass program specified
2025-04-27 02:59:47,573 - ERROR - [likitha] [patch_update] [10.5.6.9] - Patch operation failed on 10.5.6.9 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-27 02:59:47,573 - ERROR - [likitha] [patch_update] [10.4.0.46] - Patch operation failed on 10.4.0.46 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-27 02:59:47,575 - ERROR - [likitha] [patch_update] [10.4.0.13] - Patch operation failed on 10.4.0.13 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=15)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-27 07:27:40,020 - ERROR - [likitha] [http_error] [http://10.5.0.4:5002/favicon.ico] - HTTP 404 - GET /favicon.ico
2025-04-27 07:34:54,910 - INFO - [] [os_detection] [] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-27 07:34:54,911 - INFO - [likitha] [patch_update] [10.5.0.6] - Patch check on 10.5.0.6
2025-04-27 07:34:56,792 - INFO - [likitha] [patch_update] [10.5.0.6] - Command executed: sudo yum clean all && sudo yum makecache
Exit code: 1
STDOUT: None
STDERR: We trust you have received the usual lecture from the local System\nAdministrator. It usually boils down to these three things:\n\n    #1) Respect the privacy of others.\n    #2) Think before you type.\n    #3) With great power comes great responsibility.\n\nsudo: no tty present and no askpass program specified
2025-04-27 07:34:58,941 - INFO - [likitha] [patch_update] [10.5.0.6] - Command executed: sudo yum check-update || true
Exit code: 0
STDOUT: None
STDERR: We trust you have received the usual lecture from the local System\nAdministrator. It usually boils down to these three things:\n\n    #1) Respect the privacy of others.\n    #2) Think before you type.\n    #3) With great power comes great responsibility.\n\nsudo: no tty present and no askpass program specified
2025-04-27 07:35:14,043 - ERROR - [likitha] [patch_update] [10.5.6.9] - Patch operation failed on 10.5.6.9 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=20)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-27 07:35:14,043 - ERROR - [likitha] [patch_update] [10.4.0.13] - Patch operation failed on 10.4.0.13 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=20)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-27 07:35:14,043 - ERROR - [likitha] [patch_update] [10.4.0.46] - Patch operation failed on 10.4.0.46 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=20)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-27 07:40:30,067 - INFO - [] [os_detection] [] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-27 07:40:30,068 - INFO - [likitha] [patch_update] [10.5.0.6] - Patch check on 10.5.0.6
2025-04-27 07:40:32,074 - INFO - [likitha] [patch_update] [10.5.0.6] - Command executed: sudo yum clean all && sudo yum makecache fast
Exit code: 1
STDOUT: None
STDERR: We trust you have received the usual lecture from the local System\nAdministrator. It usually boils down to these three things:\n\n    #1) Respect the privacy of others.\n    #2) Think before you type.\n    #3) With great power comes great responsibility.\n\nsudo: no tty present and no askpass program specified
2025-04-27 07:40:34,347 - INFO - [likitha] [patch_update] [10.5.0.6] - Command executed: sudo yum check-update || true
Exit code: 0
STDOUT: None
STDERR: We trust you have received the usual lecture from the local System\nAdministrator. It usually boils down to these three things:\n\n    #1) Respect the privacy of others.\n    #2) Think before you type.\n    #3) With great power comes great responsibility.\n\nsudo: no tty present and no askpass program specified
2025-04-27 07:40:49,283 - ERROR - [likitha] [patch_update] [10.4.0.46] - Patch operation failed on 10.4.0.46 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=20)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-27 07:40:49,283 - ERROR - [likitha] [patch_update] [10.4.0.13] - Patch operation failed on 10.4.0.13 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=20)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-27 07:40:49,283 - ERROR - [likitha] [patch_update] [10.5.6.9] - Patch operation failed on 10.5.6.9 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=20)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-27 07:41:27,083 - INFO - [] [os_detection] [] - Command executed: cat /etc/os-release
Exit code: 0
STDOUT: NAME="CentOS Linux"\nVERSION="7 (Core)"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:7"\nHOME_URL="https://www.centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\n\nCENTOS_MANTISBT_PROJECT="CentOS-7"\nCENTOS_MANTISBT_PROJECT_VERSION="7"\nREDHAT_SUPPORT_PRODUCT="centos"\nREDHAT_SUPPORT_PRODUCT_VERSION="7"
STDERR: None
2025-04-27 07:41:27,084 - INFO - [likitha] [patch_update] [10.5.0.6] - Patch apply on 10.5.0.6
2025-04-27 07:41:29,583 - INFO - [likitha] [patch_update] [10.5.0.6] - Command executed: sudo yum clean all && sudo yum makecache fast
Exit code: 1
STDOUT: None
STDERR: We trust you have received the usual lecture from the local System\nAdministrator. It usually boils down to these three things:\n\n    #1) Respect the privacy of others.\n    #2) Think before you type.\n    #3) With great power comes great responsibility.\n\nsudo: no tty present and no askpass program specified
2025-04-27 07:41:31,327 - INFO - [likitha] [patch_update] [10.5.0.6] - Command executed: sudo yum check-update || true
Exit code: 0
STDOUT: None
STDERR: We trust you have received the usual lecture from the local System\nAdministrator. It usually boils down to these three things:\n\n    #1) Respect the privacy of others.\n    #2) Think before you type.\n    #3) With great power comes great responsibility.\n\nsudo: no tty present and no askpass program specified
2025-04-27 07:41:46,317 - ERROR - [likitha] [patch_update] [10.4.0.13] - Patch operation failed on 10.4.0.13 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=20)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-27 07:41:46,322 - ERROR - [likitha] [patch_update] [10.4.0.46] - Patch operation failed on 10.4.0.46 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=20)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-27 07:41:46,322 - ERROR - [likitha] [patch_update] [10.5.6.9] - Patch operation failed on 10.5.6.9 - timed out
Traceback (most recent call last):
  File "/home/suresh/UI-combined/ldap/j.py", line 764, in run_patch_update
    ssh.connect(ip, username=username, password=password, timeout=20)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: timed out
2025-04-29 05:48:46,749 - ERROR - [anonymous] [http_error] [http://10.5.0.4:5002/favicon.ico] - HTTP 404 - GET /favicon.ico
2025-04-29 05:50:57,122 - INFO - [likitha] [health_check] [10.5.6.9, 10.4.0.13, 10.4.0.46, 10.5.0.6] - Action COMPLETED - health_check on 4 servers
2025-04-29 06:06:33,537 - INFO - [likitha] [server_update] [10.5.6.9] - Server updated: 10.5.6.9
2025-04-29 06:17:47,871 - INFO - [likitha] [bulk_delete] [10.5.6.9, 10.4.0.13, 10.4.0.46, 10.5.0.6] - Bulk delete: 4 servers
2025-04-29 06:18:57,360 - INFO - [likitha] [server_create] [10.5.6.9] - Server created: 10.5.6.9
2025-04-29 09:25:37,694 - ERROR - [anonymous] [http_error] [http://10.5.0.4:5002/org-logo.png] - HTTP 404 - GET /org-logo.png
2025-04-29 09:27:36,010 - ERROR - [anonymous] [http_error] [http://10.5.0.4:5002/org-logo.png] - HTTP 404 - GET /org-logo.png
2025-04-29 09:27:38,638 - ERROR - [anonymous] [http_error] [http://10.5.0.4:5002/org-logo.png] - HTTP 404 - GET /org-logo.png
2025-04-29 09:46:03,892 - ERROR - [anonymous] [http_error] [http://10.5.0.4:5002/logo/org-logo.png] - HTTP 404 - GET /logo/org-logo.png
2025-04-29 10:17:41,361 - ERROR - [anonymous] [http_error] [http://10.5.0.4:5002/logo/org-logo.png] - HTTP 404 - GET /logo/org-logo.png
2025-04-29 10:17:51,842 - ERROR - [likitha] [http_error] [http://10.5.0.4:5002/org-logo.png] - HTTP 404 - GET /org-logo.png
